# Generated by Django 5.2.4 on 2025-08-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('createAt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
