# Generated by Django 5.2.4 on 2025-08-11 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_delete_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=120)),
                ('number', models.CharField(max_length=20)),
                ('neighborhood', models.CharField(blank=True, max_length=120, null=True)),
                ('complement', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField()),
                ('password', models.CharField(max_length=120)),
                ('createAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('address', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.addressmodel')),
            ],
        ),
    ]
