# Generated by Django 5.2.4 on 2025-08-11 18:23

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='country',
            field=django_countries.fields.CountryField(default='BR', max_length=2),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.addressmodel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='sex',
            field=models.TextField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')]),
        ),
    ]
