# Generated by Django 5.2.4 on 2025-08-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='priority',
            field=models.CharField(choices=[('Low', 'Baixa'), ('Medium', 'Média'), ('High', 'Alta')], default='Medium'),
        ),
    ]
